# Generated by Django 4.2.1 on 2023-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
