# Generated by Django 4.2.1 on 2023-07-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_amount_paid_purchase_supplier_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='total_price',
            new_name='total_cost',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='unit_price',
            new_name='unit_cost',
        ),
    ]
