# Generated by Django 4.2.1 on 2023-07-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_rename_total_price_purchaseitem_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
