# Generated by Django 4.2.1 on 2023-06-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_salesitem_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
