# Generated by Django 4.2.1 on 2023-06-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_salesitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
