# Generated by Django 4.2.1 on 2023-06-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_sales_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesitem',
            options={'ordering': ['product_name', 'quantity_sold', 'total_price', 'created_at', 'updated_at']},
        ),
        migrations.RenameField(
            model_name='salesitem',
            old_name='quantity',
            new_name='quantity_sold',
        ),
    ]
