# Generated by Django 4.2.1 on 2023-06-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_alter_salesitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['grandtotal', '-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='salesitem',
            options={'ordering': ['product_name', 'quantity_sold', 'total_price', '-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
